name: develop
on: push
jobs:
  verify-instrumentation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Assemble app
        run: ./gradlew assembleDebug assembleAndroidTest
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: ./gradlew connectedCheck